<script lang="ts">
  import { onMount } from 'svelte';
  import { createAuthClient } from 'better-auth/svelte';
  import { api } from '$lib/api';
  let {data}=$props();
  const auth=createAuthClient();
  let me=$state<any>(null),error=$state(''),notice=$state(''),name=$state(''),publicProfile=$state(false),teamName=$state(''),deleteReady=$state(false),sessions=$state<any[]>([]),busy=$state(false);
  async function refresh(){me=await api('me');name=me.profile?.display_name??me.user?.name??'';publicProfile=!!me.profile?.public;}
  async function act(fn:()=>Promise<unknown>,message:string){busy=true;error='';notice='';try{await fn();await refresh();notice=message;}catch(e){error=e instanceof Error?e.message:'Request failed.';}finally{busy=false;}}
  async function signIn(provider:'github'|'google'){const r=await auth.signIn.social({provider,callbackURL:'/account'});if(r.error)error='Sign-in could not be completed. Try again or choose another provider.';}
  async function signOut(){await api('guest/revoke',{});const r=await auth.signOut();if(r.error)throw Error('Sign-out could not be completed. Try again.');location.assign('/account');}
  async function listSessions(){const r=await auth.listSessions();if(r.error)throw Error('Active sessions could not be loaded. Try again.');sessions=r.data??[];}
  async function removeAccount(){const r=await auth.deleteUser({callbackURL:'/'});if(r.error)throw Error('Account deletion could not be completed. Sign in again, then retry.');location.assign('/');}
  onMount(()=>{refresh().catch(e=>error=e.message);});
</script>
<svelte:head><title>Account and profile settings — Voynich@home</title><meta name="description" content="Manage optional Voynich@home sign-in, profile visibility, team membership, sessions, and account deletion."/></svelte:head>
<div class="page narrow"><p class="eyebrow">Optional account</p><h1>Account and public-profile settings</h1><p class="lede">An account connects checked contributions across devices. Your name and team appear publicly only if you choose a public profile.</p>
{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
{#if !data.user}<section class="panel">{#if data.providers.length}<h2>Sign in</h2><p>Use GitHub or Google to connect checked contributions across devices. You can also <a href="/contribute">participate as a guest</a> when a campaign is open.</p><div class="actions">{#each data.providers as provider}<button onclick={()=>signIn(provider)}>Continue with {provider==='github'?'GitHub':'Google'}</button>{/each}</div>{:else}<h2>Account sign-in is unavailable in this preview</h2><p>Google and GitHub sign-in will open after hosted account testing is complete. Guest participation remains available whenever a campaign accepts work.</p>{/if}</section>
{:else}
<section class="panel"><div class="section-heading"><h2>Welcome, {data.user.name}.</h2><button class="secondary" disabled={busy} onclick={()=>act(signOut,'Signed out.')}>Sign out</button></div><p class="small muted">{me?.contributions?.checked??0} checked contributions · {(me?.contributions?.credit??0).toLocaleString()} credit</p>
{#if me?.guest}<button class="secondary" disabled={busy} onclick={()=>act(()=>api('claim',{}),'Contributions from this browser’s guest session are now attached to your account.')}>Attach this browser’s guest contributions</button><p class="small muted" style="margin-top:12px">Only contributions associated with this browser’s current guest session are attached. Repeating the action does not duplicate credit.</p>{/if}</section>
<section class="panel"><h2>Your public profile</h2><form class="form-stack" onsubmit={e=>{e.preventDefault();void act(()=>api('profile',{display_name:name,public:publicProfile}),'Profile saved.');}}><label>Display name<input bind:value={name} minlength="2" maxlength="48" required autocomplete="nickname"/></label><label class="check"><input type="checkbox" bind:checked={publicProfile}/>Show my name, checked credit, and team membership publicly</label><p class="small muted">Off by default. Your email and sign-in provider are never shown on rankings.</p><div><button disabled={busy}>Save profile</button></div></form>{#if me?.profile?.moderated}<p class="notice">Your profile is hidden by moderation. Contact the project owner through GitHub to request review.</p>{/if}</section>
<section class="panel"><h2>Your team</h2>{#if me?.team}<p>{me.team.name}</p><button class="secondary" disabled={busy} onclick={()=>act(()=>api('team',{leave:true}),'You left the team.')}>Leave team</button>{:else}<p>Join a team from the <a href="/community">community page</a>, or create one.</p>{/if}<form class="inline-form" style="margin-top:25px" onsubmit={e=>{e.preventDefault();void act(()=>api('team',{create:teamName}),'Team created.');}}><label>New team name<input bind:value={teamName} minlength="2" maxlength="48" required/></label><button disabled={busy}>Create team</button></form><p class="small muted" style="margin-top:15px">Team names are public. Totals include the checked credit of current members who opted into public profiles; totals change when members move teams.</p></section>
<section class="panel"><h2>Sessions and deletion</h2><div class="actions"><button class="secondary" disabled={busy} onclick={()=>act(listSessions,'Active sessions refreshed.')}>View active sessions</button><button class="secondary" disabled={busy} onclick={()=>act(async()=>{const r=await auth.revokeOtherSessions();if(r.error)throw Error('Other sessions could not be signed out. Try again.');await listSessions();},'Other devices have been signed out.')}>Sign out other devices</button></div>{#each sessions as session}<div class="check-row"><span class="small">Created {new Date(session.createdAt).toLocaleDateString()} · expires {new Date(session.expiresAt).toLocaleDateString()}</span><button class="secondary" disabled={busy} onclick={()=>act(async()=>{const r=await auth.revokeSession({token:session.token});if(r.error)throw Error('This session could not be signed out. Try again.');await listSessions();},'The selected session has been signed out.')}>Sign out session</button></div>{/each}
<div class="divider"></div><h3>Delete your account</h3><p class="small">Deletion permanently removes your account, signs out every session, and removes your public profile. Research and contribution records remain reproducible but no longer identify your account. Guest-session proofs attached to the account are revoked.</p><label class="check"><input type="checkbox" bind:checked={deleteReady}/>I want to permanently delete my account.</label><div class="actions"><button class="danger" disabled={!deleteReady||busy} onclick={()=>act(removeAccount,'Account deleted.')}>Delete my account</button></div></section>
{/if}</div>
