<script lang="ts">
  import { onMount } from 'svelte';
  import { createAuthClient } from 'better-auth/svelte';
  import { api } from '$lib/api';
  let {data}=$props();
  const auth=createAuthClient();
  let me=$state<any>(null),error=$state(''),notice=$state(''),name=$state(''),publicProfile=$state(false),teamName=$state(''),deleteReady=$state(false),sessions=$state<any[]>([]),busy=$state(false);
  async function refresh(){me=await api('me');name=me.profile?.display_name??me.user?.name??'';publicProfile=!!me.profile?.public;}
  async function act(fn:()=>Promise<unknown>,message:string){busy=true;error='';notice='';try{await fn();await refresh();notice=message;}catch(e){error=e instanceof Error?e.message:'We couldn’t complete that request. Try again.';}finally{busy=false;}}
  async function signIn(provider:'github'|'google'){const r=await auth.signIn.social({provider,callbackURL:'/account'});if(r.error)error='We couldn’t sign you in. Try again or choose another provider.';}
  async function finishChatGPT(){const response=await fetch('/api/auth/sign-in/sites-chatgpt',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const result=await response.json();if(!response.ok)throw Error(result.message??'We couldn’t finish signing you in with ChatGPT.');location.assign('/account');}
  async function signOut(){await api('guest/revoke',{});const r=await auth.signOut();if(r.error)throw Error('We couldn’t sign you out. Try again.');if(data.providers.includes('sites-chatgpt'))window.open('/signout-with-chatgpt?return_to=%2Faccount','_top');else location.assign('/account');}
  async function listSessions(){const r=await auth.listSessions();if(r.error)throw Error('We couldn’t load your active sessions. Try again.');sessions=r.data??[];}
  async function removeAccount(){const r=await auth.deleteUser({callbackURL:'/'});if(r.error)throw Error('We couldn’t delete your account. Sign in again, then retry.');location.assign('/');}
  onMount(()=>{refresh().catch(e=>error=e.message);});
</script>
<svelte:head><title>Your account · Voynich@home</title><meta name="description" content="Manage your optional Voynich@home account, public profile, team, active sessions, and account deletion."/></svelte:head>
<div class="page narrow"><p class="eyebrow">Optional account</p><h1>Your account</h1><p class="lede">An account connects your checked contributions across devices. You choose whether to publish your name, credit, and team.</p>
{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
{#if !data.user}<section class="panel">{#if data.providers.length}<h2>Sign in</h2><p>Connect checked contributions across devices. You can also <a href="/contribute">participate as a guest</a> once a campaign opens.</p><div class="actions">{#each data.providers as provider}{#if provider!=='sites-chatgpt'}<button onclick={()=>signIn(provider)}>Sign in with {provider==='github'?'GitHub':'Google'}</button>{/if}{/each}</div>{:else}<h2>Sign-in will open after account testing</h2><p>You can still participate as a guest once a campaign accepts work.</p>{/if}</section>
{:else}
<section class="panel"><div class="section-heading"><h2>Welcome, {data.user.name}.</h2><button class="secondary" disabled={busy} onclick={()=>act(signOut,'Signed out.')}>Sign out</button></div><p class="small muted">{me?.contributions?.checked??0} checked contributions · {(me?.contributions?.credit??0).toLocaleString()} credit</p>
{#if me?.guest}<button class="secondary" disabled={busy} onclick={()=>act(()=>api('claim',{}),'Contributions from this browser’s guest session are now attached to your account.')}>Attach this browser’s guest contributions</button><p class="small muted" style="margin-top:12px">Only contributions associated with this browser’s current guest session are attached. Repeating the action does not duplicate credit.</p>{/if}</section>
<section class="panel"><h2>Your public profile</h2><form class="form-stack" onsubmit={e=>{e.preventDefault();void act(()=>api('profile',{display_name:name,public:publicProfile}),'Profile saved.');}}><label>Display name<input bind:value={name} minlength="2" maxlength="48" required autocomplete="nickname"/></label><label class="check"><input type="checkbox" bind:checked={publicProfile}/>Publish my name, checked credit, and team membership</label><p class="small muted">Profiles start private. Rankings never show your email or sign-in provider.</p><div><button disabled={busy}>Save profile</button></div></form>{#if me?.profile?.moderated}<p class="notice">A moderator has hidden your profile. Ask the project owner for a review through GitHub.</p>{/if}</section>
<section class="panel"><h2>Your team</h2>{#if me?.team}<p>{me.team.name}</p><button class="secondary" disabled={busy} onclick={()=>act(()=>api('team',{leave:true}),'You left the team.')}>Leave team</button>{:else}<p>Join a team on the <a href="/community">community page</a>, or create one below.</p>{/if}<form class="inline-form" style="margin-top:25px" onsubmit={e=>{e.preventDefault();void act(()=>api('team',{create:teamName}),'Team created.');}}><label>New team name<input bind:value={teamName} minlength="2" maxlength="48" required/></label><button disabled={busy}>Create team</button></form><p class="small muted" style="margin-top:15px">Team names are public. Team totals count checked credit from current members who publish their profiles, so totals change as membership changes.</p></section>
<section class="panel"><h2>Sessions and deletion</h2><div class="actions"><button class="secondary" disabled={busy} onclick={()=>act(listSessions,'Active sessions refreshed.')}>View active sessions</button><button class="secondary" disabled={busy} onclick={()=>act(async()=>{const r=await auth.revokeOtherSessions();if(r.error)throw Error('Other sessions could not be signed out. Try again.');await listSessions();},'Other devices have been signed out.')}>Sign out other devices</button></div>{#each sessions as session}<div class="check-row"><span class="small">Created {new Date(session.createdAt).toLocaleDateString()} · expires {new Date(session.expiresAt).toLocaleDateString()}</span><button class="secondary" disabled={busy} onclick={()=>act(async()=>{const r=await auth.revokeSession({token:session.token});if(r.error)throw Error('This session could not be signed out. Try again.');await listSessions();},'The selected session has been signed out.')}>Sign out session</button></div>{/each}
<div class="divider"></div><h3>Delete your account</h3><p class="small">Deleting your account signs out every session and removes your public profile. Published research and contribution records remain available for reproduction without identifying your account. The project also revokes guest-session proofs attached to it.</p><label class="check"><input type="checkbox" bind:checked={deleteReady}/>Permanently delete my account</label><div class="actions"><button class="danger" disabled={!deleteReady||busy} onclick={()=>act(removeAccount,'Account deleted.')}>Delete my account</button></div></section>
{/if}
{#if data.providers.includes('sites-chatgpt')}<section class="panel"><h2>{data.user?'Refresh your ChatGPT sign-in':'Sign in with ChatGPT'}</h2><p>Open ChatGPT sign-in, then return here to create or refresh your site session.</p><div class="actions"><a class="button secondary" target="_top" data-sveltekit-reload href="/signin-with-chatgpt?return_to=%2Faccount">Open ChatGPT sign-in</a><button disabled={busy} onclick={()=>act(finishChatGPT,'Signed in.')}>Finish signing in</button></div></section>{/if}
</div>
