<script lang="ts">
  import { onMount } from 'svelte';
  import { createAuthClient } from 'better-auth/svelte';
  import { api } from '$lib/api';
  let {data}=$props();
  const auth=createAuthClient();
  let me=$state<any>(null),error=$state(''),notice=$state(''),name=$state(''),publicProfile=$state(false),teamName=$state(''),deleteReady=$state(false),sessions=$state<any[]>([]),busy=$state(false);
  async function refresh(){me=await api('me');name=me.profile?.display_name??me.user?.name??'';publicProfile=!!me.profile?.public;}
  async function act(fn:()=>Promise<unknown>,message:string){busy=true;error='';notice='';try{await fn();await refresh();notice=message;}catch(e){error=e instanceof Error?e.message:'Request failed.';}finally{busy=false;}}
  async function signIn(provider:'github'|'google'){const r=await auth.signIn.social({provider,callbackURL:'/account'});if(r.error)error=r.error.message??'Sign-in failed.';}
  async function signOut(){await api('guest/revoke',{});const r=await auth.signOut();if(r.error)throw Error(r.error.message);location.assign('/account');}
  async function listSessions(){const r=await auth.listSessions();if(r.error)throw Error(r.error.message);sessions=r.data??[];}
  async function removeAccount(){const r=await auth.deleteUser({callbackURL:'/'});if(r.error)throw Error(r.error.message??'Sign in again to delete your account.');location.assign('/');}
  onMount(()=>{refresh().catch(e=>error=e.message);});
</script>
<svelte:head><title>Your account — Voynich@home</title></svelte:head>
<div class="page narrow"><p class="eyebrow">Participation is always optional</p><h1>Your place in the project.</h1><p class="lede">An account connects contributions across devices. Public recognition is a separate choice.</p>
{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
{#if !data.user}<section class="panel"><h2>Sign in</h2><p>Use an existing account. You can also <a href="/contribute">contribute as a guest</a>.</p><div class="actions">{#each data.providers as provider}<button onclick={()=>signIn(provider)}>Continue with {provider==='github'?'GitHub':'Google'}</button>{/each}</div>{#if !data.providers.length}<p class="notice">Account sign-in has not been configured for this deployment. Guest participation remains available when a campaign is open.</p>{/if}</section>
{:else}
<section class="panel"><div class="section-heading"><h2>Welcome, {data.user.name}.</h2><button class="secondary" disabled={busy} onclick={()=>act(signOut,'Signed out.')}>Sign out</button></div><p class="small muted">{me?.contributions?.checked??0} checked contributions · {(me?.contributions?.credit??0).toLocaleString()} credit</p>
{#if me?.guest}<button class="secondary" disabled={busy} onclick={()=>act(()=>api('claim',{}),'This guest session is attached to your account.')}>Attach this browser’s guest contributions</button><p class="small muted" style="margin-top:12px">This proves control of the guest session in this browser. Repeating it never adds duplicate credit.</p>{/if}</section>
<section class="panel"><h2>Your public profile</h2><form class="form-stack" onsubmit={e=>{e.preventDefault();void act(()=>api('profile',{display_name:name,public:publicProfile}),'Profile saved.');}}><label>Display name<input bind:value={name} minlength="2" maxlength="48" required autocomplete="nickname"/></label><label class="check"><input type="checkbox" bind:checked={publicProfile}/>Show my name, checked credit, and team membership publicly</label><p class="small muted">Off by default. Your email and sign-in provider are never shown on rankings.</p><div><button disabled={busy}>Save profile</button></div></form>{#if me?.profile?.moderated}<p class="notice">Your profile is hidden by moderation. Contact the project owner through GitHub to request review.</p>{/if}</section>
<section class="panel"><h2>Your team</h2>{#if me?.team}<p>{me.team.name}</p><button class="secondary" disabled={busy} onclick={()=>act(()=>api('team',{leave:true}),'You left the team.')}>Leave team</button>{:else}<p>Join a team from the <a href="/community">community page</a>, or create one.</p>{/if}<form class="inline-form" style="margin-top:25px" onsubmit={e=>{e.preventDefault();void act(()=>api('team',{create:teamName}),'Team created.');}}><label>New team name<input bind:value={teamName} minlength="2" maxlength="48" required/></label><button disabled={busy}>Create team</button></form><p class="small muted" style="margin-top:15px">Team names are public. Totals include the checked credit of current members who opted into public profiles; totals change when members move teams.</p></section>
<section class="panel"><h2>Sessions and deletion</h2><div class="actions"><button class="secondary" disabled={busy} onclick={()=>act(listSessions,'Sessions refreshed.')}>View active sessions</button><button class="secondary" disabled={busy} onclick={()=>act(async()=>{const r=await auth.revokeOtherSessions();if(r.error)throw Error(r.error.message);await listSessions();},'Other sessions revoked.')}>Revoke other sessions</button></div>{#each sessions as session}<div class="check-row"><span class="small">Created {new Date(session.createdAt).toLocaleDateString()} · expires {new Date(session.expiresAt).toLocaleDateString()}</span><button class="secondary" disabled={busy} onclick={()=>act(async()=>{const r=await auth.revokeSession({token:session.token});if(r.error)throw Error(r.error.message);await listSessions();},'Session revoked.')}>Revoke</button></div>{/each}
<div class="divider"></div><h3>Delete your account</h3><p class="small">This removes your account, sessions, and public profile. Contributions and research records remain without your account identity. Guest proof tokens attached to the account are revoked.</p><label class="check"><input type="checkbox" bind:checked={deleteReady}/>I want to permanently delete my account.</label><div class="actions"><button class="danger" disabled={!deleteReady||busy} onclick={()=>act(removeAccount,'Account deleted.')}>Delete my account</button></div></section>
{/if}</div>
