[package]
name = "vah-search-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vah-search = { path = "../vah-search" }
vah-core = { path = "../vah-core" }
serde.workspace = true
serde_json.workspace = true
clap = { version = "4", features = ["derive"] }
