<script lang="ts">
  import { onMount } from 'svelte';import { api } from '$lib/api';
  let {data}=$props();let community=$state<any>(null),error=$state(''),notice=$state('');
  async function join(id:string){try{const team=community?.teams?.find((item:any)=>item.id===id);await api('team',{join:id});notice=`You joined ${team?.name??'the team'}. It appears publicly only if your profile is public.`;}catch(e){error=e instanceof Error?e.message:'Unable to join.';}}
  onMount(()=>{api('community').then(c=>community=c).catch(e=>error=e.message);});
</script>
<svelte:head><title>Community — Voynich@home</title><meta name="description" content="See public Voynich@home contributor profiles and teams based on checked computation."/></svelte:head>
<div class="page"><p class="eyebrow">Optional public recognition</p><h1>Contributors and teams</h1><p class="lede">These lists recognize checked computation. Profiles are optional, and credit measures completed work rather than scientific correctness.</p>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
<div class="two-column"><section class="panel"><h2>Contributors</h2>{#if community?.people.length}<div class="table-wrap"><table><thead><tr><th>Name</th><th>Checked work</th><th>Credit</th></tr></thead><tbody>{#each community.people as p}<tr><td>{p.display_name}</td><td>{p.checked}</td><td>{p.credit.toLocaleString()}</td></tr>{/each}</tbody></table></div>{:else}<div class="empty"><h3>No public profiles yet</h3><p>Contributors appear here only after choosing a public profile.</p></div>{/if}<p class="small muted" style="margin-top:20px">Up to 100 public profiles are shown, ordered by checked credit. <a href="/account">Review profile visibility</a>.</p></section>
<section class="panel"><h2>Teams</h2>{#if community?.teams.length}{#each community.teams as team}<article style="border-bottom:1px solid var(--line);padding:20px 0"><h3>{team.name}</h3><p class="small muted">{team.members} public members · {team.credit.toLocaleString()} credit</p>{#if data.user}<button class="secondary" onclick={()=>join(team.id)}>Join team</button>{:else if data.providers.length}<a href="/account">Sign in to join →</a>{:else}<p class="small muted">Team membership will open when account sign-in is available.</p>{/if}</article>{/each}{:else}<p class="muted">No public teams have been created.</p>{/if}{#if data.user}<a href="/account">Create or manage a team →</a>{:else if data.providers.length}<a href="/account">Sign in to create a team →</a>{:else}<p class="small muted">Team creation will open when account sign-in is available.</p>{/if}</section></div>
<p class="small muted">Names and teams may be hidden for impersonation, harassment, or spam. The project owner handles moderation; no outside endorsement is implied by participation.</p></div>
