<script lang="ts">
  import panel from '$lib/generated/development-panel.json';
  const source='https://github.com/javidmardanov/VoynichAtHome/tree/codex/public-release/research/recovery/results/development-2026-09-05';
  const names:Record<string,string>={substitution:'Letter substitution','balanced-homophonic':'Balanced homophonic','naibbe-global-permutation':'Naibbe global permutation'};
  const percent=(value:number)=>`${Number((value*100).toFixed(3))}%`;
</script>
<svelte:head><title>Development results — Voynich@home</title><meta name="description" content="Complete results and limitations from the first 3,510-search development panel."/></svelte:head>
<div class="page"><p class="eyebrow">Completed computation · 5 September 2026</p><h1>Does more search help?</h1><p class="lede">Eight starts recovered 17 of 18 development messages exactly. Sixty-four recovered the same 17. These results help us choose the next test.</p>
<div class="notice">This is method development on known messages, not a manuscript reading or an established recovery rate. There is only one case in each language, length and encoding group. The project controlled both preparation and evaluation.</div>
<section class="panel"><h2>Every message case</h2><p>Character recovery of the highest-scoring output. Beam runs once; the other columns compare 1, 8 and 64 annealing starts. The 99.995% result still contains one wrong character.</p>
<!-- svelte-ignore a11y_no_noninteractive_tabindex (The overflow region must be keyboard scrollable.) -->
<div class="table-scroll" tabindex="0" role="region" aria-label="Development character recovery table"><table><thead><tr><th scope="col">Language / characters</th><th scope="col">Encoding</th><th scope="col">Beam</th><th scope="col">1 start</th><th scope="col">8 starts</th><th scope="col">64 starts</th></tr></thead><tbody>{#each panel.rows as row}<tr><th scope="row">{row.language} / {row.length.toLocaleString('en-US')}</th><td>{names[row.family]}</td><td>{percent(row.beam)}</td><td>{percent(row['1'])}</td><td>{percent(row['8'])}</td><td>{percent(row['64'])}</td></tr>{/each}</tbody></table></div></section>
<section class="panel"><h2>What this tells us</h2><p>Three messages needed more than one start for exact recovery. None improved between eight and 64. Wrong readings could also score above both comparison texts, so a high comparison score cannot establish a correct reading.</p><p>The Naibbe variant used a global plaintext permutation and known parsing rules. It does not test unknown tables or unrestricted encodings. Development passages may overlap and were drawn from works already used while improving the method.</p><p>All 3,510 searches finished. The complete record includes shuffled and generated comparison texts, unchanged output, keys, seeds, search traces, time and sampled memory. Timings include local orchestration and concurrent development activity.</p><div class="actions"><a class="button" href={source}>Inspect methods and all records</a><a class="button secondary" href="/methods">How conclusions are reviewed</a></div></section>
<p class="small muted">Next research gate: freeze the settings, then evaluate 100 fresh message-and-key cases per reported condition. These development results do not authorize a manuscript search.</p></div>
<style>.table-scroll{overflow-x:auto;margin-top:20px}table{border-collapse:collapse;width:100%;text-align:left;font-size:.9rem}th,td{padding:12px;border-bottom:1px solid var(--line,#ddd);white-space:nowrap}thead th{font-weight:700}tbody th{font-weight:500}</style>
