<script lang="ts">
  import panel from '$lib/generated/development-panel.json';
  const source='https://github.com/javidmardanov/VoynichAtHome/tree/33debe761229e99816cd6d0f1efc1bc65c775b4d/research/recovery/results/development-2026-09-05';
  const names:Record<string,string>={substitution:'Letter substitution','balanced-homophonic':'Balanced homophonic','naibbe-global-permutation':'Naibbe global permutation'};
  const percent=(value:number)=>`${Number((value*100).toFixed(3))}%`;
</script>
<svelte:head><title>Development panel results · Voynich@home</title><meta name="description" content="Inspect all 18 known-message cases and the limits of the 3,510-search development panel."/></svelte:head>
<div class="page"><p class="eyebrow">Completed development panel · 5 September 2026</p><h1>Eight and 64 starts recovered the same 17 of 18 messages</h1><p class="lede">The project used this panel to select frozen settings for a fresh-case evaluation. That evaluation is still running and has no published report.</p>
<div class="notice">This panel developed the method on known messages. It does not report a manuscript reading or an unseen-case recovery rate. Each combination of language, length, and encoding has one case, and the project controlled both preparation and evaluation.</div>
<section class="panel"><h2>Results for all 18 cases</h2><p>Each cell shows character recovery for the highest-scoring output. Beam runs once; the other columns compare 1, 8, and 64 annealing starts. A result of 99.995% still contains one wrong character.</p>
<!-- svelte-ignore a11y_no_noninteractive_tabindex (The overflow region must be keyboard scrollable.) -->
<div class="table-scroll" tabindex="0" role="region" aria-label="Development character recovery table"><table><thead><tr><th scope="col">Language / characters</th><th scope="col">Encoding</th><th scope="col">Beam</th><th scope="col">1 start</th><th scope="col">8 starts</th><th scope="col">64 starts</th></tr></thead><tbody>{#each panel.rows as row}<tr><th scope="row">{row.language} / {row.length.toLocaleString('en-US')}</th><td>{names[row.family]}</td><td>{percent(row.beam)}</td><td>{percent(row['1'])}</td><td>{percent(row['8'])}</td><td>{percent(row['64'])}</td></tr>{/each}</tbody></table></div></section>
<section class="panel"><h2>Findings and limits</h2><p>Three messages needed more than one start for exact recovery. None improved between eight and 64 starts. Wrong readings could also score above both comparison texts, so a high comparison score cannot establish a correct reading.</p><p>The Naibbe variant used a global plaintext permutation and known parsing rules. It does not test unknown tables or unrestricted encodings. Development passages may overlap, and their source works had already informed improvements to the method.</p><p>All 3,510 searches finished. The complete record includes shuffled and generated comparison texts, unchanged output, keys, seeds, search traces, time, and sampled memory. Timings include local orchestration and concurrent development activity.</p><div class="actions"><a class="button" href={source}>Inspect the methods and records</a><a class="button secondary" href="/methods">Read the review process</a></div></section>
<p class="small muted">The fresh-case evaluation uses 100 new message-and-key cases per reported condition. An evaluated recovery rate or manuscript search must wait for its completion and published report.</p></div>
<style>.table-scroll{overflow-x:auto;margin-top:20px}table{border-collapse:collapse;width:100%;text-align:left;font-size:.9rem}th,td{padding:12px;border-bottom:1px solid var(--line,#ddd);white-space:nowrap}thead th{font-weight:700}tbody th{font-weight:500}</style>
