<script lang="ts">
  import { onDestroy } from 'svelte';import VerifyWorker from '$lib/verify.worker?worker';
  let job=$state(''),result=$state(''),busy=$state(false),error=$state(''),outcome=$state<any>(null);let worker:Worker|null=null;
  async function read(event:Event,kind:'job'|'result'){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>8000000){error='File exceeds 8 MB.';return;}if(kind==='job')job=await file.text();else result=await file.text();}
  function verify(){error='';outcome=null;try{const request={job:JSON.parse(job),result:JSON.parse(result)};worker=new VerifyWorker();busy=true;worker.onmessage=({data})=>{outcome=data;error=data.error??'';stop();};worker.onerror=()=>{error='The verification worker stopped unexpectedly.';stop();};worker.postMessage(request);}catch(e){error=e instanceof Error?e.message:'Invalid JSON.';stop();}}
  function stop(){worker?.terminate();worker=null;busy=false;}
  onDestroy(stop);
</script>
<svelte:head><title>Verify a result — Voynich@home</title><meta name="description" content="Replay a Voynich@home task locally in your browser and compare it with a recorded result."/></svelte:head>
<div class="page narrow"><p class="eyebrow">Local result verification</p><h1>Replay a recorded task</h1><p class="lede">Download a task’s scientific input and result record from its campaign page, then choose both files below. This browser reruns the task with the matching project software and checks search keys and scores.</p><div class="notice">Verification begins only after you select both files and click the button. The files stay in this browser. A matching replay confirms the recorded computation under the same conditions; historical interpretation requires separate evidence.</div>
<section class="panel"><form class="form-stack" onsubmit={e=>{e.preventDefault();verify();}}><label>Scientific input file (JSON)<input type="file" accept="application/json,.json" onchange={e=>read(e,'job')} disabled={busy}/></label><label>Result record file (JSON)<input type="file" accept="application/json,.json" onchange={e=>read(e,'result')} disabled={busy}/></label><div class="actions"><button disabled={busy||!job||!result}>{busy?'Replaying the task…':'Replay and compare'}</button><button type="button" class="secondary" disabled={!busy} onclick={stop}>Stop replay</button></div></form>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if outcome&&!outcome.error}<div class="notice" role="status"><strong>{outcome.matches?'The replay matches the complete recorded result.':'The replay differs from the recorded result.'}</strong><p class="small" style="margin-top:12px">{#if outcome.score!==undefined}Recomputed score: {outcome.score}<br/>{/if}Replayed result digest: <code>{outcome.result_digest}</code></p></div>{#if outcome.plaintext}<details><summary>Unchanged decoder output and mapping</summary><pre>{outcome.plaintext}</pre><pre>{JSON.stringify(outcome.key)}</pre></details>{:else}<details><summary>Complete replayed result</summary><pre>{JSON.stringify(outcome.replay,null,2)}</pre></details>{/if}{/if}</section><p class="small muted">This browser tool accepts version 1 search, generation, and verification inputs. Older fixtures use the versioned native tools and legacy test vectors documented with the <a href="/downloads">source and build instructions</a>.</p></div>
