<script lang="ts">
  import { onDestroy } from 'svelte';import VerifyWorker from '$lib/verify.worker?worker';
  let job=$state(''),result=$state(''),busy=$state(false),error=$state(''),outcome=$state<any>(null);let worker:Worker|null=null;
  async function read(event:Event,kind:'job'|'result'){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>8000000){error='File exceeds 8 MB.';return;}if(kind==='job')job=await file.text();else result=await file.text();}
  function verify(){error='';outcome=null;try{const request={job:JSON.parse(job),result:JSON.parse(result)};worker=new VerifyWorker();busy=true;worker.onmessage=({data})=>{outcome=data;error=data.error??'';stop();};worker.onerror=()=>{error='The verification worker stopped unexpectedly.';stop();};worker.postMessage(request);}catch(e){error=e instanceof Error?e.message:'Invalid JSON.';stop();}}
  function stop(){worker?.terminate();worker=null;busy=false;}
  onDestroy(stop);
</script>
<svelte:head><title>Verify a result — Voynich@home</title></svelte:head>
<div class="page narrow"><p class="eyebrow">Reproduce before interpreting</p><h1>Check the actual result.</h1><p class="lede">Load a search job and its result. The browser checks the key, recomputes its score, and replays the declared search with the approved kernel.</p><div class="notice">Verification happens in this browser after you click. Files are not uploaded. Matching output establishes reproducibility; it does not establish a correct reading of the manuscript.</div>
<section class="panel"><form class="form-stack" onsubmit={e=>{e.preventDefault();verify();}}><label>Search job (vah-search-1)<input type="file" accept="application/json,.json" onchange={e=>read(e,'job')} disabled={busy}/></label><label>Result record<input type="file" accept="application/json,.json" onchange={e=>read(e,'result')} disabled={busy}/></label><div class="actions"><button disabled={busy||!job||!result}>{busy?'Replaying search…':'Verify and replay'}</button><button type="button" class="secondary" disabled={!busy} onclick={stop}>Stop verification</button></div></form>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if outcome&&!outcome.error}<div class="notice" role="status"><strong>{outcome.matches?'The replay matches the complete result.':'The replay does not match this result.'}</strong><p class="small" style="margin-top:12px">Recomputed score: {outcome.score}<br/>Result identity: <code>{outcome.result_digest}</code></p></div><details><summary>Unchanged decoder output and mapping</summary><pre>{outcome.plaintext}</pre><pre>{JSON.stringify(outcome.key)}</pre></details>{/if}</section><p class="small muted">Older kernel fixtures remain reproducible through the versioned native tools and legacy test vectors. This browser tool accepts the current search contract only.</p></div>
