<script lang="ts">
  import { onMount } from 'svelte';import { api } from '$lib/api';
  let dashboard=$state<any>(null),operating=$state<any>(null),error=$state(''),notice=$state(''),reason=$state('Release checks in progress.'),payload=$state('{\n  "action": "register-release"\n}'),busy=$state(false);
  let portable=$state<any>(null);
  async function exportBackup(){busy=true;error='';try{portable=await api('owner',{action:'portable-backup'});}catch(e){error=String(e);}finally{busy=false;}}
  async function refresh(){[dashboard,operating]=await Promise.all([api('owner'),api('status')]);}
  function completed(result:unknown){if(!result||typeof result!=='object')return 'Action completed.';const value=result as Record<string,unknown>;if(value.status)return `Campaign status changed to ${String(value.status).replaceAll('_',' ')}.`;if(value.state)return `Release status changed to ${String(value.state).replaceAll('_',' ')}.`;if(value.stopped===true)return 'New assignments are paused.';if(value.stopped===false)return 'New assignments are open.';if(value.retry===true)return 'A funded result check has been queued.';if(value.imported===true)return value.duplicate?'This record was already imported. No duplicate was created.':'The record was imported.';return 'Action completed.';}
  async function act(input:unknown){busy=true;error='';notice='';try{const result=await api('owner',input);notice=completed(result);await refresh();}catch(e){error=e instanceof Error?e.message:'Action failed.';}finally{busy=false;}}
  async function importFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file){if(file.size>8000000){error='Import exceeds 8 MB.';return;}payload=await file.text();}}
  onMount(()=>{refresh().catch(e=>error=e.message);});
</script>
<svelte:head><title>Owner controls — Voynich@home</title></svelte:head>
<div class="page"><p class="eyebrow">Release authority</p><h1>Project operations</h1><p class="lede">Campaigns and software releases require explicit owner actions. The deployment’s assignment setting must also permit new work.</p>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
<section class="panel"><h2>Assignment controls</h2><p>{operating?.assignments_enabled?'Assignments are open.':'Assignments are paused.'} {operating?.reason}</p><label>Message shown on the public status page<input bind:value={reason} maxlength="200"/></label><div class="actions"><button class="danger" disabled={busy} onclick={()=>act({action:'control',stopped:true,reason})}>Pause new assignments</button><button disabled={busy} onclick={()=>act({action:'control',stopped:false,reason})}>Open assignments</button><button class="secondary" onclick={async()=>{try{await api('owner/validate',{});notice='Pending result checks have been queued.';}catch(e){error=e instanceof Error?e.message:'Pending checks could not be queued.';}}}>Retry pending checks</button></div><p class="small muted">Clients read this setting every 30 seconds. Their Stop button ends local computation immediately. Capacity reserved for issued work remains available for its result checks.</p></section>
<section class="panel"><h2>Monthly reserve</h2><pre>{JSON.stringify(operating?.budget,null,2)}</pre><p class="small muted">Every imported work unit reserves 30,000 ms for trusted replay. This application limits the initial reserve to 1,000,000 ms and 25 simultaneous leases. Provider billing is separate; alerts are not a hard spending cap.</p></section>
<section class="panel"><h2>Campaigns and releases</h2><div class="table-wrap"><table><thead><tr><th>Campaign</th><th>Status</th><th>Action</th></tr></thead><tbody>{#each dashboard?.campaigns??[] as c}<tr><td>{c.title}</td><td>{c.status}</td><td>{#if c.status!=='completed'}<button class="secondary" disabled={busy} onclick={()=>act({action:'campaign-state',id:c.id,status:c.status==='active'?'paused':'active'})}>{c.status==='active'?'Pause':'Open'}</button>{/if}</td></tr>{/each}</tbody></table></div>{#each dashboard?.releases??[] as release}<div class="check-row" style="margin-top:20px"><code>{release.id}</code><span>{release.state}</span><button class="danger" disabled={busy||release.state==='revoked'} onclick={()=>act({action:'revoke-release',id:release.id})}>Revoke release</button></div>{/each}</section>
<section class="panel"><h2>Import an operating record</h2><p class="small muted">Use a versioned campaign, task, budget, or moderation record from the operating guide. Search inputs never contain the concealed answer.</p><label>Choose a JSON file<input type="file" accept="application/json,.json" onchange={importFile}/></label><form class="form-stack" style="margin-top:20px" onsubmit={e=>{e.preventDefault();try{void act(JSON.parse(payload));}catch{error='Invalid JSON.';}}}><label>Record<textarea bind:value={payload} spellcheck="false"></textarea></label><div><button disabled={busy}>Validate and apply record</button></div></form></section>
<section class="panel"><h2>Operational failures</h2>{#each dashboard?.errors??[] as item}<div><code>{item.id}</code><p>{item.validation_error}</p>{#if item.state==='validation_error'}<button class="secondary" disabled={busy} onclick={()=>act({action:'retry-validation',id:item.id})}>Allow funded validation retry</button>{:else if item.state==='delivery_exhausted'}<p class="small">Review the delivery records, then use an <code>extend-delivery</code> operation with a reason to permit two more attempts. The previous attempts are preserved.</p>{:else}<p class="small">Repeat the identical unit import to finish writing its input. This campaign cannot open while an import is incomplete.</p>{/if}</div>{:else}<p>No recorded validation errors.</p>{/each}</section>
<section class="panel"><h2>Private recovery export</h2><p>A complete copy needs the manifest and every listed object. Store it privately: the database contains account and session data. Refresh the deletion records before restoring an older copy.</p><button disabled={busy} onclick={exportBackup}>Prepare portable backup</button>{#if portable}<p><a download="voynich-backup-manifest.json" href={'data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(portable.manifest))}>Save backup manifest</a></p><ul>{#each portable.manifest.objects as object}<li><a download href={portable.download_url+'?key='+encodeURIComponent(object.key)}>{object.key}</a> · {object.size} bytes</li>{/each}</ul><p class="small">Import each verified object through a maintenance operation, then restore the recorded database snapshot. The operating guide covers integrity checks and session revocation.</p>{/if}</section>
<details><summary>Recent owner actions</summary><pre>{JSON.stringify(dashboard?.audit,null,2)}</pre></details></div>
