<script lang="ts">
  import { onMount } from 'svelte';import { api } from '$lib/api';
  let dashboard=$state<any>(null),operating=$state<any>(null),error=$state(''),notice=$state(''),reason=$state('Release checks in progress.'),payload=$state('{\n  "action": "register-release"\n}'),busy=$state(false);
  async function refresh(){[dashboard,operating]=await Promise.all([api('owner'),api('status')]);}
  async function act(input:unknown){busy=true;error='';notice='';try{const result=await api('owner',input);notice=JSON.stringify(result);await refresh();}catch(e){error=e instanceof Error?e.message:'Action failed.';}finally{busy=false;}}
  async function importFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file){if(file.size>8000000){error='Import exceeds 8 MB.';return;}payload=await file.text();}}
  onMount(()=>{refresh().catch(e=>error=e.message);});
</script>
<svelte:head><title>Owner controls — Voynich@home</title></svelte:head>
<div class="page"><p class="eyebrow">Release authority</p><h1>Operate the project.</h1><p class="lede">Campaigns and releases require explicit owner actions. The environment’s assignment switch is an additional gate.</p>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status"><code>{notice}</code></p>{/if}
<section class="panel"><h2>Assignment controls</h2><p>{operating?.assignments_enabled?'Assignments enabled.':'Assignments paused.'} {operating?.reason}</p><label>Public operating message<input bind:value={reason} maxlength="200"/></label><div class="actions"><button class="danger" disabled={busy} onclick={()=>act({action:'control',stopped:true,reason})}>Stop new assignments</button><button disabled={busy} onclick={()=>act({action:'control',stopped:false,reason})}>Allow assignments</button><button class="secondary" onclick={async()=>{try{await api('owner/validate',{});notice='Pending checks queued.';}catch(e){error=String(e);}}}>Retry pending checks</button></div><p class="small muted">Clients check the operating switch every 30 seconds. Their Stop button terminates local computation immediately. Issued work keeps its validation reserve.</p></section>
<section class="panel"><h2>Monthly reserve</h2><pre>{JSON.stringify(operating?.budget,null,2)}</pre><p class="small muted">Every imported work unit reserves 30,000 ms for trusted replay. This application limits the initial reserve to 1,000,000 ms and 25 simultaneous leases. Provider billing is separate; alerts are not a hard spending cap.</p></section>
<section class="panel"><h2>Campaigns and releases</h2><div class="table-wrap"><table><thead><tr><th>Campaign</th><th>Status</th><th>Action</th></tr></thead><tbody>{#each dashboard?.campaigns??[] as c}<tr><td>{c.title}</td><td>{c.status}</td><td>{#if c.status!=='completed'}<button class="secondary" disabled={busy} onclick={()=>act({action:'campaign-state',id:c.id,status:c.status==='active'?'paused':'active'})}>{c.status==='active'?'Pause':'Open'}</button>{/if}</td></tr>{/each}</tbody></table></div>{#each dashboard?.releases??[] as release}<div class="check-row" style="margin-top:20px"><code>{release.id}</code><span>{release.state}</span><button class="danger" disabled={busy||release.state==='revoked'} onclick={()=>act({action:'revoke-release',id:release.id})}>Revoke release</button></div>{/each}</section>
<section class="panel"><h2>Import a versioned operation</h2><p class="small muted">Use a campaign, unit, budget, or moderation record from the operating guide. Worker answers are never part of search inputs.</p><label>Read JSON file<input type="file" accept="application/json,.json" onchange={importFile}/></label><form class="form-stack" style="margin-top:20px" onsubmit={e=>{e.preventDefault();try{void act(JSON.parse(payload));}catch{error='Invalid JSON.';}}}><label>Operation<textarea bind:value={payload} spellcheck="false"></textarea></label><div><button disabled={busy}>Validate and apply operation</button></div></form></section>
<section class="panel"><h2>Operational failures</h2>{#each dashboard?.errors??[] as item}<div><code>{item.id}</code><p>{item.validation_error}</p><button class="secondary" disabled={busy} onclick={()=>act({action:'retry-validation',id:item.id})}>Allow validation retry</button></div>{:else}<p>No recorded validation errors.</p>{/each}</section>
<details><summary>Recent owner actions</summary><pre>{JSON.stringify(dashboard?.audit,null,2)}</pre></details></div>
