<svelte:head><title>Methods — Voynich@home</title></svelte:head>
<div class="page narrow prose"><p class="eyebrow">How we turn computation into evidence</p><h1>Test a claim.<br/>Keep the record.</h1><p class="lede">We search defined possibilities, measure where the search succeeds and fails, and publish enough detail for someone else to repeat it.</p>
<h2>First, recover known messages</h2><p>Latin and Italian are a practical starting scope. Their inclusion does not imply that either is the manuscript’s language. Our search uses compact character-sequence models trained on separate source works. The decoder’s output is never rewritten into fluent prose.</p><p>The program compares ordinary substitution, homophonic substitution, and documented encodings that expand letters into groups. It tests 1,000, 5,000, and 20,000 normalized characters, and compares 1, 8, and 64 independent starts where the method supports restarts.</p><p>A development panel selects settings. The final study requires frozen settings and 100 fresh message-and-key cases per reported condition, with the same search budgets applied to shuffled and generated controls. Until those tests are complete, the development observations remain limited.</p>
<h2>Preserve the construction</h2><p>Naibbe is a documented encoding with several Voynich-like properties. Its author does not claim that it solves the manuscript. Our implementation preserves the published tables and notices, and rejects ambiguous output. Our key-randomized extension is labeled separately: after parsing the known symbol-group structure, it reduces to substitution. Recovering that extension is not evidence of an unrestricted verbose-cipher solution.</p><p><a href="https://www.michaelgreshko.com/naibbe-cipher">Michael Greshko’s Naibbe explanation</a> · <a href="https://github.com/javidmardanov/VoynichAtHome/tree/codex/public-release/third_party/naibbe">Imported implementation and terms</a></p>
<h2>Then, define a manuscript search</h2><p>A manuscript campaign needs a useful operating range established by recovery tests. It must declare its exact transcription, included passages, grouping and space rules, language resources, algorithm, seeds, budget, comparisons, and stopping conditions.</p><p>Pages, lines, paragraphs, uncertainty, and excluded material remain visible. Major manuscript text groups are studied separately before combining them. A candidate includes its actual mapping and unchanged decoder output, including unparsed symbols and exceptions.</p>
<h2 id="validation">Check the execution and the candidate</h2><p>The initial coordinator uses duplicate execution and a full trusted replay for each work unit. It recomputes the search output and score before awarding credit. A disagreement receives no credit; a runtime interruption is an operational failure and says nothing about a hypothesis.</p><p>Anonymous browser identifiers do not prove independent people or machines. Agreement by itself is not proof of honest execution. Browser verification checks reproducibility, not the historical truth of a reading.</p><p>Credit is a fixed estimate: the ceiling of search evaluations × normalized ciphertext symbols ÷ 1,000. It does not depend on reported runtime, persuasive words, or scientific importance. Team totals use current, publicly visible membership.</p>
<h2 id="corrections">Correct the scientific foundation</h2><p>The former “Rule C” did not justify its claimed 1% error guarantee. We removed that claim, corrected replicate-count and metric inconsistencies, and stopped interpreting an empty adaptive search as exclusion of an entire continuous parameter domain.</p><p>Earlier work used the whole manuscript during development. Current manuscript results are exploratory. For formal testing of a fully specified generator, the conditional test calibrates fresh simulated target texts with the same declared procedure; its assumptions and finite simulation limits are recorded.</p><p><a href="https://github.com/javidmardanov/VoynichAtHome/blob/codex/public-release/docs/research/acceptance-rule-review.md">Acceptance-rule review</a> · <a href="https://github.com/javidmardanov/VoynichAtHome/blob/codex/public-release/docs/SCIENTIFIC-CORRECTIONS.md">Corrections and interpretation</a></p>
<h2>Review and propose</h2><p>The human project owner remains the release authority. Current development checks are maintained within the project; we do not describe them as independently administered. Outside researchers can strengthen the work through reproduction and criticism.</p><p>A proposal should state a concrete question, data rights, a reproducible method, positive and negative controls, a computation budget, and a decision rule. We publish bounded negative results as well as candidates.</p><a class="button secondary" href="https://github.com/javidmardanov/VoynichAtHome/issues/new?template=experiment-proposal.yml">Propose an experiment ↗</a>
</div>
